---

- name: Install
  hosts: localhost
  connection: local
  become: yes
  vars_files:
    - config.build.yaml
    - config.defaults.yaml
    - ../config.yaml

- import_playbook: pre_requisites.yaml

- import_playbook: pre_nginx.yaml
  when: is_nginx_enabled == true

- import_playbook: pre_apuppet.yaml

- import_playbook: pre_certbot.yaml
  when: is_certbot_enabled and is_nginx_enabled

- import_playbook: pre_webadmin.yaml
